#include <precompiled.hpp>
#include "callbacks_impl.hpp"

IMPLEMENT_CALLBACK_MGR_METHOD(Init);
IMPLEMENT_CALLBACK_MGR_METHOD(Done);
IMPLEMENT_CALLBACK_MGR_METHOD(OnMenuBuild);
IMPLEMENT_CALLBACK_MGR_METHOD(OnMenuInit);
IMPLEMENT_CALLBACK_MGR_METHOD(OnDrawUI);
IMPLEMENT_CALLBACK_MGR_METHOD(OnDllFrame);
IMPLEMENT_CALLBACK_MGR_METHOD(OnGameFrame);
IMPLEMENT_CALLBACK_MGR_METHOD(OnMonsterSpawn);
IMPLEMENT_CALLBACK_MGR_METHOD(OnGuiPageChange);